"use client"

import { useState, useEffect } from "react"
import { useSearchParams } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { ArrowLeft, Play } from "lucide-react"
import Link from "next/link"
import { AvatarSelector } from "@/components/avatar-selector"
import { useRouter } from "next/navigation"
import { roomManager } from "@/lib/room-manager"

export default function JoinPage() {
  const searchParams = useSearchParams()
  const router = useRouter()
  const [username, setUsername] = useState("")
  const [roomCode, setRoomCode] = useState("")
  const [selectedAvatar, setSelectedAvatar] = useState("🦄") // Set default avatar
  const [isJoining, setIsJoining] = useState(false)
  const [roomError, setRoomError] = useState("")
  const [playerId] = useState(() => {
    // Check if we're on the client side
    if (typeof window === 'undefined') {
      return Math.random().toString(36).substr(2, 9)
    }
    
    // Try to get existing player ID from localStorage first
    const storedPlayer = localStorage.getItem("currentPlayer")
    if (storedPlayer) {
      try {
        const player = JSON.parse(storedPlayer)
        return player.id || Math.random().toString(36).substr(2, 9)
      } catch (error) {
        console.error("Error parsing stored player:", error)
      }
    }
    return Math.random().toString(36).substr(2, 9)
  })

  useEffect(() => {
    const roomFromUrl = searchParams.get("room")
    if (roomFromUrl) {
      setRoomCode(roomFromUrl.toUpperCase())
      // If there's a room in URL, clear any previous player data to allow fresh join
      if (typeof window !== 'undefined') {
        localStorage.removeItem("currentPlayer")
      }
    }

    // Only auto-redirect if there's no room in URL and user has valid session
    if (!roomFromUrl && typeof window !== 'undefined') {
      const checkExistingSession = async () => {
        const storedPlayer = localStorage.getItem("currentPlayer")
        if (storedPlayer) {
          try {
            const player = JSON.parse(storedPlayer)
            if (player.roomCode) {
              // Check if the room still exists and user is still in it
              const room = await roomManager.getRoom(player.roomCode)
              if (room && room.players.find((p: any) => p.id === player.id)) {
                // User is still in the room, redirect to waiting room
                console.log("[Join] Auto-redirecting to existing room:", player.roomCode)
                router.push(`/waiting-room/${player.roomCode}`)
                return
              } else {
                // Room doesn't exist or user is not in it, clear stored data
                console.log("[Join] Clearing invalid player data")
                localStorage.removeItem("currentPlayer")
              }
            }
          } catch (error) {
            console.error("Error parsing stored player info:", error)
            localStorage.removeItem("currentPlayer")
          }
        }
      }
      
      checkExistingSession()
    }
  }, [searchParams, router])

  const handleJoinRoom = async () => {
    if (!username.trim() || !roomCode.trim()) return

    setIsJoining(true)
    setRoomError("")

    console.log("[Join] Attempting to join room:", roomCode)

    await new Promise((resolve) => setTimeout(resolve, 500))

    const room = await roomManager.getRoom(roomCode)
    console.log("[Join] Room found:", room)

    if (!room) {
      console.log("[Join] Room not found for code:", roomCode)
      setRoomError("Room not found. Please check the room code.")
      setIsJoining(false)
      return
    }

    if (room.gameStarted) {
      setRoomError("This game has already started. Please join a new room.")
      setIsJoining(false)
      return
    }

    // Check if player already exists in room
    const existingPlayer = room.players.find((p: any) => p.id === playerId)
    
    let success: boolean
    if (existingPlayer) {
      // Player exists, use rejoinRoom
      success = await roomManager.rejoinRoom(roomCode, {
        id: playerId,
        username: username.trim(),
        avatar: selectedAvatar,
      })
    } else {
      // New player, use joinRoom
      success = await roomManager.joinRoom(roomCode, {
        username: username.trim(),
        avatar: selectedAvatar,
      })
    }

    console.log("[Join] Rejoin result:", success)

    if (success) {
      // Get the actual player ID from the room (in case it was generated by joinRoom)
      const updatedRoom = await roomManager.getRoom(roomCode)
      const actualPlayer = updatedRoom?.players.find((p: any) => 
        p.username === username.trim() && p.avatar === selectedAvatar
      )
      const finalPlayerId = actualPlayer?.id || playerId
      
      // Store player info locally (only on client side)
      if (typeof window !== 'undefined') {
        localStorage.setItem(
          "currentPlayer",
          JSON.stringify({
            id: finalPlayerId,
            username: username.trim(),
            avatar: selectedAvatar,
            roomCode,
          }),
        )
      }

      console.log("[Join] Successfully joined, redirecting to waiting room")
      // Redirect to waiting room route
      router.push(`/waiting-room/${roomCode}`)
    } else {
      setRoomError("Failed to join room. Please try again.")
    }

    setIsJoining(false)
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-indigo-900">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          <Link href="/">
            <Button variant="ghost" size="sm" className="text-white hover:bg-white/10">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Home
            </Button>
          </Link>
          <div className="flex items-center gap-2">
            <Play className="h-6 w-6 text-blue-400" />
            <h1 className="text-2xl font-bold text-white">Join a Game</h1>
          </div>
        </div>

        <div className="max-w-md mx-auto">
            <Card>
              <CardHeader className="text-center">
                <CardTitle className="text-xl">Join Room</CardTitle>
                <CardDescription>
                  {roomCode ? "Enter your username to join the game" : "Enter your details to join the game"}
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-2">
                  <Label htmlFor="username">Username</Label>
                  <Input
                    id="username"
                    placeholder="Enter your username"
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                  />
                </div>

                {!searchParams.get("room") && (
                  <div className="space-y-2">
                    <Label htmlFor="roomCode">Room Code</Label>
                    <Input
                      id="roomCode"
                      placeholder="Enter room code"
                      value={roomCode}
                      onChange={(e) => setRoomCode(e.target.value.toUpperCase())}
                      className="uppercase"
                    />
                    {roomError && <p className="text-sm text-destructive">{roomError}</p>}
                  </div>
                )}

                {searchParams.get("room") && (
                  <div className="space-y-2">
                    <Label>Room Code</Label>
                    <div className="p-3 bg-muted rounded-md text-center font-mono text-lg font-semibold">
                      {roomCode}
                    </div>
                    {roomError && <p className="text-sm text-destructive">{roomError}</p>}
                  </div>
                )}

                <div className="space-y-2">
                  <Label>Choose Avatar (Optional)</Label>
                  <AvatarSelector selectedAvatar={selectedAvatar} onAvatarSelect={setSelectedAvatar} />
                  <p className="text-xs text-muted-foreground">Default: 🦄 Unicorn</p>
                </div>

                <Button
                  className="w-full"
                  onClick={handleJoinRoom}
                  disabled={!username.trim() || !roomCode.trim() || isJoining}
                >
                  {isJoining ? "Joining..." : "Join Room"}
                </Button>
              </CardContent>
            </Card>
          </div>

      </div>
    </div>
  )
}
