export interface Question {
  id: number
  question: string
  options: string[]
  correct: number
  explanation?: string
}

export interface Quiz {
  id: string
  title: string
  description: string
  icon: string
  color: string
  difficulty: "Easy" | "Medium" | "Hard"
  questions: Question[]
}

export const quizzes: Quiz[] = [
  {
    id: "math-basic",
    title: "Basic Mathematics",
    description: "Addition, subtraction, multiplication, and division",
    icon: "Calculator",
    color: "bg-chart-1/10 text-chart-1",
    difficulty: "Easy",
    questions: [
      { id: 1, question: "What is 5 + 3?", options: ["6", "7", "8", "9"], correct: 2 },
      { id: 2, question: "What is 12 - 7?", options: ["4", "5", "6", "7"], correct: 1 },
      { id: 3, question: "What is 4 × 6?", options: ["20", "22", "24", "26"], correct: 2 },
      { id: 4, question: "What is 15 ÷ 3?", options: ["3", "4", "5", "6"], correct: 2 },
      { id: 5, question: "What is 9 + 6?", options: ["14", "15", "16", "17"], correct: 1 },
      { id: 6, question: "What is 20 - 8?", options: ["10", "11", "12", "13"], correct: 2 },
      { id: 7, question: "What is 7 × 3?", options: ["19", "20", "21", "22"], correct: 2 },
      { id: 8, question: "What is 24 ÷ 4?", options: ["5", "6", "7", "8"], correct: 1 },
      { id: 9, question: "What is 8 + 7?", options: ["14", "15", "16", "17"], correct: 1 },
      { id: 10, question: "What is 16 - 9?", options: ["6", "7", "8", "9"], correct: 1 },
      { id: 11, question: "What is 5 × 8?", options: ["35", "40", "45", "50"], correct: 1 },
      { id: 12, question: "What is 36 ÷ 6?", options: ["5", "6", "7", "8"], correct: 1 },
      { id: 13, question: "What is 11 + 9?", options: ["19", "20", "21", "22"], correct: 1 },
      { id: 14, question: "What is 25 - 7?", options: ["17", "18", "19", "20"], correct: 1 },
      { id: 15, question: "What is 6 × 9?", options: ["52", "54", "56", "58"], correct: 1 },
      { id: 16, question: "What is 42 ÷ 7?", options: ["5", "6", "7", "8"], correct: 1 },
      { id: 17, question: "What is 13 + 8?", options: ["20", "21", "22", "23"], correct: 1 },
      { id: 18, question: "What is 30 - 12?", options: ["16", "17", "18", "19"], correct: 2 },
      { id: 19, question: "What is 8 × 7?", options: ["54", "56", "58", "60"], correct: 1 },
      { id: 20, question: "What is 45 ÷ 9?", options: ["4", "5", "6", "7"], correct: 1 },
      { id: 21, question: "What is 14 + 6?", options: ["19", "20", "21", "22"], correct: 1 },
      { id: 22, question: "What is 22 - 5?", options: ["16", "17", "18", "19"], correct: 1 },
      { id: 23, question: "What is 9 × 4?", options: ["34", "36", "38", "40"], correct: 1 },
      { id: 24, question: "What is 32 ÷ 8?", options: ["3", "4", "5", "6"], correct: 1 },
      { id: 25, question: "What is 17 + 5?", options: ["21", "22", "23", "24"], correct: 1 },
      { id: 26, question: "What is 28 - 9?", options: ["18", "19", "20", "21"], correct: 1 },
      { id: 27, question: "What is 7 × 6?", options: ["40", "42", "44", "46"], correct: 1 },
      { id: 28, question: "What is 35 ÷ 5?", options: ["6", "7", "8", "9"], correct: 1 },
      { id: 29, question: "What is 19 + 4?", options: ["22", "23", "24", "25"], correct: 1 },
      { id: 30, question: "What is 26 - 8?", options: ["17", "18", "19", "20"], correct: 1 },
      { id: 31, question: "What is 6 × 7?", options: ["40", "42", "44", "46"], correct: 1 },
      { id: 32, question: "What is 48 ÷ 6?", options: ["7", "8", "9", "10"], correct: 1 },
      { id: 33, question: "What is 15 + 7?", options: ["21", "22", "23", "24"], correct: 1 },
      { id: 34, question: "What is 31 - 6?", options: ["24", "25", "26", "27"], correct: 1 },
      { id: 35, question: "What is 8 × 9?", options: ["70", "72", "74", "76"], correct: 1 },
      { id: 36, question: "What is 54 ÷ 9?", options: ["5", "6", "7", "8"], correct: 1 },
      { id: 37, question: "What is 18 + 9?", options: ["26", "27", "28", "29"], correct: 1 },
      { id: 38, question: "What is 33 - 7?", options: ["25", "26", "27", "28"], correct: 1 },
      { id: 39, question: "What is 9 × 6?", options: ["52", "54", "56", "58"], correct: 1 },
      { id: 40, question: "What is 63 ÷ 7?", options: ["8", "9", "10", "11"], correct: 1 },
      { id: 41, question: "What is 21 + 8?", options: ["28", "29", "30", "31"], correct: 1 },
      { id: 42, question: "What is 35 - 9?", options: ["25", "26", "27", "28"], correct: 1 },
      { id: 43, question: "What is 7 × 8?", options: ["54", "56", "58", "60"], correct: 1 },
      { id: 44, question: "What is 56 ÷ 8?", options: ["6", "7", "8", "9"], correct: 1 },
      { id: 45, question: "What is 23 + 9?", options: ["31", "32", "33", "34"], correct: 1 },
      { id: 46, question: "What is 37 - 8?", options: ["28", "29", "30", "31"], correct: 1 },
      { id: 47, question: "What is 6 × 8?", options: ["46", "48", "50", "52"], correct: 1 },
      { id: 48, question: "What is 49 ÷ 7?", options: ["6", "7", "8", "9"], correct: 1 },
      { id: 49, question: "What is 25 + 6?", options: ["30", "31", "32", "33"], correct: 1 },
      { id: 50, question: "What is 39 - 7?", options: ["31", "32", "33", "34"], correct: 1 },
    ],
  },
  {
    id: "science-nature",
    title: "Science & Nature",
    description: "Animals, plants, and natural phenomena",
    icon: "Beaker",
    color: "bg-chart-2/10 text-chart-2",
    difficulty: "Medium",
    questions: [
      {
        id: 1,
        question: "Which planet is closest to the Sun?",
        options: ["Venus", "Mercury", "Earth", "Mars"],
        correct: 1,
      },
      { id: 2, question: "What do bees make?", options: ["Milk", "Honey", "Butter", "Cheese"], correct: 1 },
      { id: 3, question: "How many legs does a spider have?", options: ["6", "8", "10", "12"], correct: 1 },
      {
        id: 4,
        question: "What gas do plants absorb from the air?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        correct: 1,
      },
      {
        id: 5,
        question: "Which animal is known as the King of the Jungle?",
        options: ["Tiger", "Lion", "Elephant", "Bear"],
        correct: 1,
      },
      {
        id: 6,
        question: "What is the largest mammal in the world?",
        options: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
        correct: 1,
      },
      { id: 7, question: "How many chambers does a human heart have?", options: ["2", "3", "4", "5"], correct: 2 },
      {
        id: 8,
        question: "What is the hardest natural substance?",
        options: ["Gold", "Iron", "Diamond", "Silver"],
        correct: 2,
      },
      { id: 9, question: "Which bird cannot fly?", options: ["Eagle", "Penguin", "Sparrow", "Robin"], correct: 1 },
      {
        id: 10,
        question: "What is the main source of energy for Earth?",
        options: ["Moon", "Sun", "Stars", "Wind"],
        correct: 1,
      },
      {
        id: 11,
        question: "How many bones are in an adult human body?",
        options: ["106", "206", "306", "406"],
        correct: 1,
      },
      {
        id: 12,
        question: "What do caterpillars turn into?",
        options: ["Beetles", "Butterflies", "Bees", "Ants"],
        correct: 1,
      },
      {
        id: 13,
        question: "Which organ pumps blood through the body?",
        options: ["Brain", "Heart", "Liver", "Lungs"],
        correct: 1,
      },
      {
        id: 14,
        question: "What is the fastest land animal?",
        options: ["Lion", "Horse", "Cheetah", "Deer"],
        correct: 2,
      },
      {
        id: 15,
        question: "How many days does it take for Earth to orbit the Sun?",
        options: ["300", "365", "400", "500"],
        correct: 1,
      },
      {
        id: 16,
        question: "What is the largest planet in our solar system?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        correct: 2,
      },
      {
        id: 17,
        question: "Which animal changes color to blend with surroundings?",
        options: ["Chameleon", "Tiger", "Zebra", "Giraffe"],
        correct: 0,
      },
      {
        id: 18,
        question: "What do we call baby frogs?",
        options: ["Puppies", "Tadpoles", "Kittens", "Cubs"],
        correct: 1,
      },
      { id: 19, question: "How many wings does a bee have?", options: ["2", "4", "6", "8"], correct: 1 },
      {
        id: 20,
        question: "What is the smallest bone in the human body?",
        options: ["Toe bone", "Finger bone", "Ear bone", "Nose bone"],
        correct: 2,
      },
      { id: 21, question: "Which tree produces acorns?", options: ["Pine", "Oak", "Maple", "Birch"], correct: 1 },
      { id: 22, question: "What is the chemical symbol for water?", options: ["H2O", "CO2", "O2", "NaCl"], correct: 0 },
      {
        id: 23,
        question: "How many teeth does an adult human typically have?",
        options: ["28", "30", "32", "34"],
        correct: 2,
      },
      {
        id: 24,
        question: "Which animal is known for its black and white stripes?",
        options: ["Tiger", "Leopard", "Zebra", "Panda"],
        correct: 2,
      },
      {
        id: 25,
        question: "What is the largest organ in the human body?",
        options: ["Heart", "Brain", "Liver", "Skin"],
        correct: 3,
      },
      { id: 26, question: "How many eyes does a typical spider have?", options: ["2", "4", "6", "8"], correct: 3 },
      {
        id: 27,
        question: "What do we call animals that eat only plants?",
        options: ["Carnivores", "Herbivores", "Omnivores", "Insectivores"],
        correct: 1,
      },
      {
        id: 28,
        question: "Which planet is known as the Red Planet?",
        options: ["Venus", "Mars", "Jupiter", "Saturn"],
        correct: 1,
      },
      {
        id: 29,
        question: "What is the process by which plants make food?",
        options: ["Respiration", "Photosynthesis", "Digestion", "Circulation"],
        correct: 1,
      },
      { id: 30, question: "How many legs does an insect have?", options: ["4", "6", "8", "10"], correct: 1 },
      {
        id: 31,
        question: "What is the tallest animal in the world?",
        options: ["Elephant", "Giraffe", "Horse", "Camel"],
        correct: 1,
      },
      {
        id: 32,
        question: "Which gas makes up most of Earth's atmosphere?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        correct: 2,
      },
      {
        id: 33,
        question: "What do we call animals that are active at night?",
        options: ["Diurnal", "Nocturnal", "Crepuscular", "Matinal"],
        correct: 1,
      },
      { id: 34, question: "How many chambers does a fish heart have?", options: ["1", "2", "3", "4"], correct: 1 },
      {
        id: 35,
        question: "What is the study of weather called?",
        options: ["Geology", "Biology", "Meteorology", "Astronomy"],
        correct: 2,
      },
      {
        id: 36,
        question: "Which animal can live both in water and on land?",
        options: ["Fish", "Bird", "Amphibian", "Reptile"],
        correct: 2,
      },
      {
        id: 37,
        question: "What is the center of an atom called?",
        options: ["Electron", "Proton", "Neutron", "Nucleus"],
        correct: 3,
      },
      { id: 38, question: "How many pairs of ribs do humans have?", options: ["10", "12", "14", "16"], correct: 1 },
      {
        id: 39,
        question: "What is the smallest unit of life?",
        options: ["Atom", "Cell", "Molecule", "Organ"],
        correct: 1,
      },
      {
        id: 40,
        question: "Which animal is known for building dams?",
        options: ["Otter", "Beaver", "Muskrat", "Raccoon"],
        correct: 1,
      },
      {
        id: 41,
        question: "What is the boiling point of water?",
        options: ["90°C", "100°C", "110°C", "120°C"],
        correct: 1,
      },
      { id: 42, question: "How many sides does a snowflake have?", options: ["4", "5", "6", "8"], correct: 2 },
      {
        id: 43,
        question: "What is the largest type of penguin?",
        options: ["King", "Emperor", "Adelie", "Chinstrap"],
        correct: 1,
      },
      {
        id: 44,
        question: "Which part of the plant absorbs water?",
        options: ["Leaves", "Stem", "Roots", "Flowers"],
        correct: 2,
      },
      {
        id: 45,
        question: "What is the speed of light?",
        options: ["300,000 km/s", "150,000 km/s", "450,000 km/s", "600,000 km/s"],
        correct: 0,
      },
      { id: 46, question: "How many bones do sharks have?", options: ["0", "50", "100", "200"], correct: 0 },
      {
        id: 47,
        question: "What is the largest bird in the world?",
        options: ["Eagle", "Ostrich", "Albatross", "Condor"],
        correct: 1,
      },
      {
        id: 48,
        question: "Which blood type is known as the universal donor?",
        options: ["A", "B", "AB", "O"],
        correct: 3,
      },
      {
        id: 49,
        question: "What is the study of earthquakes called?",
        options: ["Geology", "Seismology", "Meteorology", "Oceanography"],
        correct: 1,
      },
      { id: 50, question: "How many hearts does an octopus have?", options: ["1", "2", "3", "4"], correct: 2 },
    ],
  },
  {
    id: "geography-world",
    title: "World Geography",
    description: "Countries, capitals, and landmarks",
    icon: "Globe",
    color: "bg-chart-3/10 text-chart-3",
    difficulty: "Medium",
    questions: [
      {
        id: 1,
        question: "What is the capital of France?",
        options: ["London", "Berlin", "Paris", "Madrid"],
        correct: 2,
      },
      {
        id: 2,
        question: "Which is the largest continent?",
        options: ["Africa", "Asia", "Europe", "North America"],
        correct: 1,
      },
      {
        id: 3,
        question: "What is the longest river in the world?",
        options: ["Amazon", "Nile", "Mississippi", "Yangtze"],
        correct: 1,
      },
      {
        id: 4,
        question: "Which country has the most time zones?",
        options: ["USA", "Russia", "China", "Canada"],
        correct: 1,
      },
      {
        id: 5,
        question: "What is the smallest country in the world?",
        options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
        correct: 1,
      },
      {
        id: 6,
        question: "Which mountain range contains Mount Everest?",
        options: ["Andes", "Rockies", "Alps", "Himalayas"],
        correct: 3,
      },
      {
        id: 7,
        question: "What is the capital of Australia?",
        options: ["Sydney", "Melbourne", "Canberra", "Perth"],
        correct: 2,
      },
      {
        id: 8,
        question: "Which desert is the largest in the world?",
        options: ["Sahara", "Gobi", "Kalahari", "Antarctic"],
        correct: 3,
      },
      {
        id: 9,
        question: "What is the deepest ocean?",
        options: ["Atlantic", "Pacific", "Indian", "Arctic"],
        correct: 1,
      },
      {
        id: 10,
        question: "Which country is known as the Land of the Rising Sun?",
        options: ["China", "Japan", "Korea", "Thailand"],
        correct: 1,
      },
      {
        id: 11,
        question: "What is the capital of Canada?",
        options: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
        correct: 2,
      },
      {
        id: 12,
        question: "Which river flows through London?",
        options: ["Seine", "Thames", "Rhine", "Danube"],
        correct: 1,
      },
      {
        id: 13,
        question: "What is the highest waterfall in the world?",
        options: ["Niagara", "Victoria", "Angel Falls", "Iguazu"],
        correct: 2,
      },
      {
        id: 14,
        question: "Which country has the shape of a boot?",
        options: ["Spain", "Italy", "Greece", "Portugal"],
        correct: 1,
      },
      {
        id: 15,
        question: "What is the capital of Brazil?",
        options: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"],
        correct: 2,
      },
      {
        id: 16,
        question: "Which sea is the saltiest?",
        options: ["Red Sea", "Dead Sea", "Black Sea", "Caspian Sea"],
        correct: 1,
      },
      {
        id: 17,
        question: "What is the largest island in the world?",
        options: ["Madagascar", "Greenland", "New Guinea", "Borneo"],
        correct: 1,
      },
      {
        id: 18,
        question: "Which country is both in Europe and Asia?",
        options: ["Russia", "Turkey", "Kazakhstan", "All of the above"],
        correct: 3,
      },
      {
        id: 19,
        question: "What is the capital of Egypt?",
        options: ["Alexandria", "Cairo", "Luxor", "Aswan"],
        correct: 1,
      },
      {
        id: 20,
        question: "Which strait separates Europe and Africa?",
        options: ["Bering", "Gibraltar", "Hormuz", "Malacca"],
        correct: 1,
      },
      {
        id: 21,
        question: "What is the largest lake in the world?",
        options: ["Superior", "Victoria", "Caspian Sea", "Baikal"],
        correct: 2,
      },
      {
        id: 22,
        question: "Which country has the most natural lakes?",
        options: ["Finland", "Canada", "Sweden", "Russia"],
        correct: 1,
      },
      {
        id: 23,
        question: "What is the capital of India?",
        options: ["Mumbai", "Kolkata", "New Delhi", "Chennai"],
        correct: 2,
      },
      {
        id: 24,
        question: "Which volcano destroyed Pompeii?",
        options: ["Etna", "Vesuvius", "Stromboli", "Vulcano"],
        correct: 1,
      },
      {
        id: 25,
        question: "What is the driest place on Earth?",
        options: ["Sahara Desert", "Atacama Desert", "Death Valley", "Gobi Desert"],
        correct: 1,
      },
      {
        id: 26,
        question: "Which country is known as the Pearl of the Orient?",
        options: ["Thailand", "Philippines", "Malaysia", "Singapore"],
        correct: 1,
      },
      {
        id: 27,
        question: "What is the capital of South Korea?",
        options: ["Busan", "Seoul", "Incheon", "Daegu"],
        correct: 1,
      },
      {
        id: 28,
        question: "Which river is sacred to Hindus?",
        options: ["Yamuna", "Ganges", "Indus", "Brahmaputra"],
        correct: 1,
      },
      {
        id: 29,
        question: "What is the largest country in South America?",
        options: ["Argentina", "Brazil", "Peru", "Colombia"],
        correct: 1,
      },
      {
        id: 30,
        question: "Which city is known as the Big Apple?",
        options: ["Los Angeles", "Chicago", "New York", "Boston"],
        correct: 2,
      },
      {
        id: 31,
        question: "What is the capital of Mexico?",
        options: ["Guadalajara", "Monterrey", "Mexico City", "Tijuana"],
        correct: 2,
      },
      {
        id: 32,
        question: "Which country has the most islands?",
        options: ["Norway", "Finland", "Sweden", "Canada"],
        correct: 1,
      },
      {
        id: 33,
        question: "What is the smallest ocean?",
        options: ["Indian", "Atlantic", "Arctic", "Southern"],
        correct: 2,
      },
      {
        id: 34,
        question: "Which country is known as the Roof of the World?",
        options: ["Nepal", "Tibet", "Bhutan", "Afghanistan"],
        correct: 1,
      },
      {
        id: 35,
        question: "What is the capital of Argentina?",
        options: ["Córdoba", "Rosario", "Buenos Aires", "Mendoza"],
        correct: 2,
      },
      {
        id: 36,
        question: "Which peninsula is Spain located on?",
        options: ["Italian", "Balkan", "Iberian", "Scandinavian"],
        correct: 2,
      },
      {
        id: 37,
        question: "What is the longest mountain range in the world?",
        options: ["Himalayas", "Rockies", "Andes", "Alps"],
        correct: 2,
      },
      {
        id: 38,
        question: "Which country is known as the Land of Fire and Ice?",
        options: ["Norway", "Iceland", "Greenland", "Finland"],
        correct: 1,
      },
      {
        id: 39,
        question: "What is the capital of Nigeria?",
        options: ["Lagos", "Kano", "Abuja", "Ibadan"],
        correct: 2,
      },
      {
        id: 40,
        question: "Which sea is between Italy and the Balkans?",
        options: ["Tyrrhenian", "Adriatic", "Ionian", "Aegean"],
        correct: 1,
      },
      {
        id: 41,
        question: "What is the largest city in the world by population?",
        options: ["Tokyo", "Delhi", "Shanghai", "São Paulo"],
        correct: 0,
      },
      {
        id: 42,
        question: "Which country has the longest coastline?",
        options: ["Russia", "Canada", "Norway", "Chile"],
        correct: 1,
      },
      {
        id: 43,
        question: "What is the capital of Thailand?",
        options: ["Phuket", "Chiang Mai", "Bangkok", "Pattaya"],
        correct: 2,
      },
      {
        id: 44,
        question: "Which African country was never colonized?",
        options: ["Ethiopia", "Liberia", "Both A and B", "Morocco"],
        correct: 2,
      },
      {
        id: 45,
        question: "What is the deepest point on Earth?",
        options: ["Mariana Trench", "Puerto Rico Trench", "Java Trench", "Peru-Chile Trench"],
        correct: 0,
      },
      {
        id: 46,
        question: "Which country is known as the Hermit Kingdom?",
        options: ["Bhutan", "North Korea", "Myanmar", "Laos"],
        correct: 1,
      },
      {
        id: 47,
        question: "What is the capital of Peru?",
        options: ["Cusco", "Arequipa", "Lima", "Trujillo"],
        correct: 2,
      },
      {
        id: 48,
        question: "Which strait connects the Atlantic and Pacific oceans?",
        options: ["Bering", "Drake Passage", "Strait of Magellan", "Both B and C"],
        correct: 3,
      },
      {
        id: 49,
        question: "What is the largest country in Africa?",
        options: ["Libya", "Chad", "Algeria", "Sudan"],
        correct: 2,
      },
      {
        id: 50,
        question: "Which city straddles two continents?",
        options: ["Istanbul", "Cairo", "Casablanca", "Suez"],
        correct: 0,
      },
    ],
  },
  // Continue with remaining quizzes...
  {
    id: "english-vocab",
    title: "English Vocabulary",
    description: "Words, meanings, and grammar",
    icon: "BookOpen",
    color: "bg-chart-4/10 text-chart-4",
    difficulty: "Easy",
    questions: [
      {
        id: 1,
        question: "What does 'enormous' mean?",
        options: ["Very small", "Very large", "Very fast", "Very slow"],
        correct: 1,
      },
      {
        id: 2,
        question: "Which word is a synonym for 'happy'?",
        options: ["Sad", "Angry", "Joyful", "Tired"],
        correct: 2,
      },
      {
        id: 3,
        question: "What is the plural of 'child'?",
        options: ["Childs", "Children", "Childes", "Childrens"],
        correct: 1,
      },
      { id: 4, question: "What does 'ancient' mean?", options: ["New", "Very old", "Broken", "Colorful"], correct: 1 },
      { id: 5, question: "Which word rhymes with 'cat'?", options: ["Dog", "Hat", "Bird", "Fish"], correct: 1 },
      // Add 45 more questions...
      { id: 6, question: "What is the opposite of 'hot'?", options: ["Warm", "Cool", "Cold", "Freezing"], correct: 2 },
      {
        id: 7,
        question: "Which word means 'very tired'?",
        options: ["Exhausted", "Excited", "Happy", "Hungry"],
        correct: 0,
      },
      {
        id: 8,
        question: "What is the past tense of 'run'?",
        options: ["Runned", "Ran", "Running", "Runs"],
        correct: 1,
      },
      {
        id: 9,
        question: "Which word is an adjective?",
        options: ["Quickly", "Beautiful", "Running", "Yesterday"],
        correct: 1,
      },
      { id: 10, question: "What does 'gigantic' mean?", options: ["Tiny", "Huge", "Fast", "Slow"], correct: 1 },
      // Continue with remaining 40 questions for brevity...
      {
        id: 11,
        question: "What is a synonym for 'smart'?",
        options: ["Dumb", "Intelligent", "Lazy", "Slow"],
        correct: 1,
      },
      { id: 12, question: "Which word is a noun?", options: ["Run", "Quickly", "Beautiful", "Table"], correct: 3 },
      {
        id: 13,
        question: "What does 'transparent' mean?",
        options: ["Opaque", "Clear", "Colorful", "Heavy"],
        correct: 1,
      },
      { id: 14, question: "What is the plural of 'mouse'?", options: ["Mouses", "Mice", "Mouse", "Meese"], correct: 1 },
      {
        id: 15,
        question: "Which word means 'to look at carefully'?",
        options: ["Glance", "Examine", "Ignore", "Avoid"],
        correct: 1,
      },
      // Adding more questions to reach 50
      {
        id: 16,
        question: "What is the opposite of 'light'?",
        options: ["Bright", "Heavy", "Dark", "Both B and C"],
        correct: 3,
      },
      { id: 17, question: "Which word is a verb?", options: ["Book", "Red", "Jump", "Happiness"], correct: 2 },
      {
        id: 18,
        question: "What does 'fragile' mean?",
        options: ["Strong", "Easily broken", "Heavy", "Colorful"],
        correct: 1,
      },
      { id: 19, question: "What is the past tense of 'eat'?", options: ["Eated", "Ate", "Eating", "Eats"], correct: 1 },
      { id: 20, question: "Which word rhymes with 'night'?", options: ["Day", "Light", "Dark", "Moon"], correct: 1 },
      {
        id: 21,
        question: "What does 'magnificent' mean?",
        options: ["Terrible", "Wonderful", "Small", "Boring"],
        correct: 1,
      },
      {
        id: 22,
        question: "What is a synonym for 'angry'?",
        options: ["Happy", "Furious", "Calm", "Peaceful"],
        correct: 1,
      },
      {
        id: 23,
        question: "Which word is an adverb?",
        options: ["Quick", "Quickly", "Quickness", "Quicker"],
        correct: 1,
      },
      {
        id: 24,
        question: "What does 'invisible' mean?",
        options: ["Very visible", "Cannot be seen", "Very small", "Very large"],
        correct: 1,
      },
      { id: 25, question: "What is the plural of 'foot'?", options: ["Foots", "Feet", "Feets", "Foot"], correct: 1 },
      {
        id: 26,
        question: "Which word means 'to make better'?",
        options: ["Worsen", "Improve", "Destroy", "Ignore"],
        correct: 1,
      },
      {
        id: 27,
        question: "What is the opposite of 'empty'?",
        options: ["Full", "Hollow", "Vacant", "Bare"],
        correct: 0,
      },
      {
        id: 28,
        question: "Which word is a preposition?",
        options: ["Under", "Running", "Beautiful", "Happiness"],
        correct: 0,
      },
      { id: 29, question: "What does 'enormous' mean?", options: ["Tiny", "Huge", "Medium", "Small"], correct: 1 },
      { id: 30, question: "What is the past tense of 'go'?", options: ["Goed", "Went", "Going", "Goes"], correct: 1 },
      { id: 31, question: "Which word rhymes with 'tree'?", options: ["Branch", "Leaf", "Free", "Root"], correct: 2 },
      { id: 32, question: "What does 'ancient' mean?", options: ["Modern", "Very old", "New", "Recent"], correct: 1 },
      { id: 33, question: "What is a synonym for 'big'?", options: ["Small", "Large", "Tiny", "Little"], correct: 1 },
      {
        id: 34,
        question: "Which word is a conjunction?",
        options: ["And", "Running", "Beautiful", "Table"],
        correct: 0,
      },
      { id: 35, question: "What does 'delicious' mean?", options: ["Tasty", "Terrible", "Sour", "Bitter"], correct: 0 },
      {
        id: 36,
        question: "What is the plural of 'tooth'?",
        options: ["Tooths", "Teeth", "Teeths", "Tooth"],
        correct: 1,
      },
      { id: 37, question: "Which word means 'very cold'?", options: ["Hot", "Warm", "Freezing", "Cool"], correct: 2 },
      {
        id: 38,
        question: "What is the opposite of 'loud'?",
        options: ["Noisy", "Quiet", "Sound", "Voice"],
        correct: 1,
      },
      {
        id: 39,
        question: "Which word is an interjection?",
        options: ["Wow", "Running", "Beautiful", "Table"],
        correct: 0,
      },
      { id: 40, question: "What does 'brilliant' mean?", options: ["Dull", "Very bright", "Dark", "Dim"], correct: 1 },
      { id: 41, question: "What is the past tense of 'see'?", options: ["Seed", "Saw", "Seeing", "Sees"], correct: 1 },
      { id: 42, question: "Which word rhymes with 'blue'?", options: ["Red", "Green", "True", "Yellow"], correct: 2 },
      { id: 43, question: "What does 'enormous' mean?", options: ["Small", "Huge", "Medium", "Tiny"], correct: 1 },
      { id: 44, question: "What is a synonym for 'fast'?", options: ["Slow", "Quick", "Lazy", "Tired"], correct: 1 },
      { id: 45, question: "Which word is a pronoun?", options: ["Book", "Red", "Jump", "She"], correct: 3 },
      {
        id: 46,
        question: "What does 'transparent' mean?",
        options: ["Opaque", "See-through", "Solid", "Heavy"],
        correct: 1,
      },
      {
        id: 47,
        question: "What is the plural of 'goose'?",
        options: ["Gooses", "Geese", "Goose", "Geeses"],
        correct: 1,
      },
      { id: 48, question: "Which word means 'to begin'?", options: ["End", "Start", "Finish", "Stop"], correct: 1 },
      {
        id: 49,
        question: "What is the opposite of 'rough'?",
        options: ["Smooth", "Bumpy", "Hard", "Tough"],
        correct: 0,
      },
      {
        id: 50,
        question: "Which word is an article?",
        options: ["The", "Running", "Beautiful", "Happiness"],
        correct: 0,
      },
    ],
  },
  // Adding more quiz categories with abbreviated question sets for brevity
  {
    id: "history-world",
    title: "World History",
    description: "Important events and historical figures",
    icon: "Trophy",
    color: "bg-chart-5/10 text-chart-5",
    difficulty: "Hard",
    questions: [
      {
        id: 1,
        question: "Who was the first President of the United States?",
        options: ["Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"],
        correct: 1,
      },
      { id: 2, question: "In which year did World War II end?", options: ["1944", "1945", "1946", "1947"], correct: 1 },
      {
        id: 3,
        question: "Who built the first pyramid in Egypt?",
        options: ["Khufu", "Imhotep", "Djoser", "Khafre"],
        correct: 2,
      },
      {
        id: 4,
        question: "Which empire was ruled by Julius Caesar?",
        options: ["Greek", "Roman", "Persian", "Egyptian"],
        correct: 1,
      },
      { id: 5, question: "When did the Berlin Wall fall?", options: ["1987", "1988", "1989", "1990"], correct: 2 },
      // Continue with 45 more history questions...
      {
        id: 6,
        question: "Who discovered America in 1492?",
        options: ["Vasco da Gama", "Christopher Columbus", "Ferdinand Magellan", "Marco Polo"],
        correct: 1,
      },
      {
        id: 7,
        question: "Which ancient wonder was in Alexandria?",
        options: ["Hanging Gardens", "Lighthouse", "Colossus", "Mausoleum"],
        correct: 1,
      },
      {
        id: 8,
        question: "Who was known as the Iron Lady?",
        options: ["Queen Elizabeth", "Margaret Thatcher", "Indira Gandhi", "Golda Meir"],
        correct: 1,
      },
      { id: 9, question: "In which year did the Titanic sink?", options: ["1910", "1911", "1912", "1913"], correct: 2 },
      {
        id: 10,
        question: "Who painted the ceiling of the Sistine Chapel?",
        options: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"],
        correct: 1,
      },
      // Adding more questions to reach 50 total
      {
        id: 11,
        question: "Which war was fought from 1914-1918?",
        options: ["World War II", "World War I", "Civil War", "Revolutionary War"],
        correct: 1,
      },
      {
        id: 12,
        question: "Who was the first man on the moon?",
        options: ["Buzz Aldrin", "Neil Armstrong", "John Glenn", "Alan Shepard"],
        correct: 1,
      },
      {
        id: 13,
        question: "Which city was the capital of the Byzantine Empire?",
        options: ["Rome", "Athens", "Constantinople", "Alexandria"],
        correct: 2,
      },
      {
        id: 14,
        question: "Who wrote the Declaration of Independence?",
        options: ["George Washington", "Benjamin Franklin", "Thomas Jefferson", "John Adams"],
        correct: 2,
      },
      {
        id: 15,
        question: "In which year did the French Revolution begin?",
        options: ["1789", "1790", "1791", "1792"],
        correct: 0,
      },
      {
        id: 16,
        question: "Who was the last Pharaoh of Egypt?",
        options: ["Cleopatra", "Nefertiti", "Hatshepsut", "Ankhesenamun"],
        correct: 0,
      },
      {
        id: 17,
        question: "Which empire was known for its road system?",
        options: ["Greek", "Roman", "Persian", "Mongol"],
        correct: 1,
      },
      {
        id: 18,
        question: "Who invented the printing press?",
        options: ["Johannes Gutenberg", "Leonardo da Vinci", "Galileo", "Newton"],
        correct: 0,
      },
      {
        id: 19,
        question: "Which battle ended Napoleon's rule?",
        options: ["Austerlitz", "Waterloo", "Trafalgar", "Leipzig"],
        correct: 1,
      },
      {
        id: 20,
        question: "Who was the first Emperor of China?",
        options: ["Qin Shi Huang", "Han Wudi", "Tang Taizong", "Kangxi"],
        correct: 0,
      },
      // Continue with remaining questions for brevity...
      {
        id: 21,
        question: "In which year did India gain independence?",
        options: ["1946", "1947", "1948", "1949"],
        correct: 1,
      },
      {
        id: 22,
        question: "Who led the Mongol Empire?",
        options: ["Kublai Khan", "Genghis Khan", "Ogedei Khan", "Batu Khan"],
        correct: 1,
      },
      {
        id: 23,
        question: "Which civilization built Machu Picchu?",
        options: ["Aztec", "Maya", "Inca", "Olmec"],
        correct: 2,
      },
      {
        id: 24,
        question: "Who was known as the Sun King?",
        options: ["Louis XIV", "Louis XVI", "Napoleon", "Charles V"],
        correct: 0,
      },
      {
        id: 25,
        question: "In which year did the Cold War end?",
        options: ["1989", "1990", "1991", "1992"],
        correct: 2,
      },
      {
        id: 26,
        question: "Who founded the Mongol Empire?",
        options: ["Kublai Khan", "Genghis Khan", "Ogedei Khan", "Chagatai Khan"],
        correct: 1,
      },
      {
        id: 27,
        question: "Which ancient library was in Egypt?",
        options: ["Pergamon", "Alexandria", "Babylon", "Athens"],
        correct: 1,
      },
      {
        id: 28,
        question: "Who was the first woman to fly solo across the Atlantic?",
        options: ["Bessie Coleman", "Amelia Earhart", "Jacqueline Cochran", "Harriet Quimby"],
        correct: 1,
      },
      {
        id: 29,
        question: "In which year did the American Civil War end?",
        options: ["1863", "1864", "1865", "1866"],
        correct: 2,
      },
      {
        id: 30,
        question: "Who was known as the Maid of Orleans?",
        options: ["Marie Antoinette", "Joan of Arc", "Catherine de Medici", "Anne of Brittany"],
        correct: 1,
      },
      {
        id: 31,
        question: "Which empire controlled most of Europe under Charlemagne?",
        options: ["Roman", "Holy Roman", "Byzantine", "Frankish"],
        correct: 3,
      },
      {
        id: 32,
        question: "Who discovered penicillin?",
        options: ["Louis Pasteur", "Alexander Fleming", "Marie Curie", "Jonas Salk"],
        correct: 1,
      },
      {
        id: 33,
        question: "In which year did the Russian Revolution occur?",
        options: ["1916", "1917", "1918", "1919"],
        correct: 1,
      },
      {
        id: 34,
        question: "Who was the first person to circumnavigate the globe?",
        options: ["Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "Francis Drake"],
        correct: 2,
      },
      {
        id: 35,
        question: "Which ancient Greek city-state was known for its military?",
        options: ["Athens", "Sparta", "Corinth", "Thebes"],
        correct: 1,
      },
      {
        id: 36,
        question: "Who painted the Mona Lisa?",
        options: ["Michelangelo", "Leonardo da Vinci", "Raphael", "Botticelli"],
        correct: 1,
      },
      {
        id: 37,
        question: "In which year did the Great Wall of China construction begin?",
        options: ["7th century BC", "5th century BC", "3rd century BC", "1st century BC"],
        correct: 0,
      },
      {
        id: 38,
        question: "Who was the first person to reach the South Pole?",
        options: ["Robert Scott", "Roald Amundsen", "Ernest Shackleton", "Richard Byrd"],
        correct: 1,
      },
      {
        id: 39,
        question: "Which revolution began in 1789?",
        options: ["American", "French", "Russian", "Industrial"],
        correct: 1,
      },
      {
        id: 40,
        question: "Who was known as the Father of History?",
        options: ["Thucydides", "Herodotus", "Xenophon", "Plutarch"],
        correct: 1,
      },
      {
        id: 41,
        question: "In which year did World War I begin?",
        options: ["1913", "1914", "1915", "1916"],
        correct: 1,
      },
      {
        id: 42,
        question: "Who was the last Emperor of Russia?",
        options: ["Alexander III", "Nicholas II", "Alexander II", "Nicholas I"],
        correct: 1,
      },
      {
        id: 43,
        question: "Which ancient civilization invented writing?",
        options: ["Egyptian", "Sumerian", "Chinese", "Indus"],
        correct: 1,
      },
      {
        id: 44,
        question: "Who led the Indian independence movement?",
        options: ["Jawaharlal Nehru", "Mahatma Gandhi", "Subhas Chandra Bose", "Sardar Patel"],
        correct: 1,
      },
      {
        id: 45,
        question: "In which year did the Renaissance begin?",
        options: ["13th century", "14th century", "15th century", "16th century"],
        correct: 1,
      },
      {
        id: 46,
        question: "Who was known as the Conqueror?",
        options: ["Alexander", "Caesar", "William", "Napoleon"],
        correct: 2,
      },
      {
        id: 47,
        question: "Which empire was ruled by Akbar?",
        options: ["Ottoman", "Mughal", "Safavid", "Maratha"],
        correct: 1,
      },
      {
        id: 48,
        question: "Who invented the telephone?",
        options: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"],
        correct: 1,
      },
      {
        id: 49,
        question: "In which year did the Berlin Wall construction begin?",
        options: ["1960", "1961", "1962", "1963"],
        correct: 1,
      },
      {
        id: 50,
        question: "Who was the first woman Prime Minister of Britain?",
        options: ["Margaret Thatcher", "Theresa May", "Elizabeth I", "Victoria"],
        correct: 0,
      },
    ],
  },
  // Adding remaining quiz categories with sample questions
  {
    id: "art-culture",
    title: "Art & Culture",
    description: "Famous artists, paintings, and cultural facts",
    icon: "Palette",
    color: "bg-primary/10 text-primary",
    difficulty: "Medium",
    questions: [
      {
        id: 1,
        question: "Who painted 'Starry Night'?",
        options: ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Leonardo da Vinci"],
        correct: 1,
      },
      { id: 2, question: "Which instrument has 88 keys?", options: ["Guitar", "Violin", "Piano", "Flute"], correct: 2 },
      {
        id: 3,
        question: "What is the most famous painting in the Louvre?",
        options: ["The Scream", "Mona Lisa", "Starry Night", "Girl with a Pearl Earring"],
        correct: 1,
      },
      {
        id: 4,
        question: "Who composed 'The Four Seasons'?",
        options: ["Mozart", "Beethoven", "Vivaldi", "Bach"],
        correct: 2,
      },
      {
        id: 5,
        question: "Which art movement did Picasso help create?",
        options: ["Impressionism", "Cubism", "Surrealism", "Expressionism"],
        correct: 1,
      },
      // Continue with 45 more art and culture questions...
      {
        id: 6,
        question: "What does 'Renaissance' mean?",
        options: ["Rebirth", "Revolution", "Reform", "Renewal"],
        correct: 0,
      },
      {
        id: 7,
        question: "Who sculpted 'David'?",
        options: ["Donatello", "Michelangelo", "Bernini", "Rodin"],
        correct: 1,
      },
      {
        id: 8,
        question: "Which dance originated in Argentina?",
        options: ["Salsa", "Tango", "Flamenco", "Waltz"],
        correct: 1,
      },
      {
        id: 9,
        question: "What is the highest male singing voice?",
        options: ["Bass", "Baritone", "Tenor", "Countertenor"],
        correct: 3,
      },
      {
        id: 10,
        question: "Who painted 'The Persistence of Memory'?",
        options: ["Salvador Dalí", "René Magritte", "Max Ernst", "Joan Miró"],
        correct: 0,
      },
      // Adding more questions to reach 50
      {
        id: 11,
        question: "Which museum houses the Mona Lisa?",
        options: ["Metropolitan", "Louvre", "Uffizi", "Prado"],
        correct: 1,
      },
      {
        id: 12,
        question: "What type of art is Auguste Rodin famous for?",
        options: ["Painting", "Sculpture", "Photography", "Architecture"],
        correct: 1,
      },
      {
        id: 13,
        question: "Which composer wrote 'Swan Lake'?",
        options: ["Stravinsky", "Tchaikovsky", "Prokofiev", "Rachmaninoff"],
        correct: 1,
      },
      {
        id: 14,
        question: "What is the art of beautiful handwriting called?",
        options: ["Typography", "Calligraphy", "Lithography", "Photography"],
        correct: 1,
      },
      {
        id: 15,
        question: "Who painted 'The Girl with a Pearl Earring'?",
        options: ["Rembrandt", "Vermeer", "Rubens", "van Dyck"],
        correct: 1,
      },
      {
        id: 16,
        question: "Which instrument is Yo-Yo Ma famous for playing?",
        options: ["Violin", "Piano", "Cello", "Flute"],
        correct: 2,
      },
      {
        id: 17,
        question: "What does 'opera' mean in Italian?",
        options: ["Song", "Work", "Story", "Drama"],
        correct: 1,
      },
      {
        id: 18,
        question: "Who designed the Eiffel Tower?",
        options: ["Le Corbusier", "Gustave Eiffel", "Antoni Gaudí", "Frank Lloyd Wright"],
        correct: 1,
      },
      {
        id: 19,
        question: "Which art style uses dots to create images?",
        options: ["Cubism", "Impressionism", "Pointillism", "Fauvism"],
        correct: 2,
      },
      {
        id: 20,
        question: "What is the lowest female singing voice?",
        options: ["Soprano", "Mezzo-soprano", "Alto", "Contralto"],
        correct: 3,
      },
      {
        id: 21,
        question: "Who painted 'American Gothic'?",
        options: ["Grant Wood", "Edward Hopper", "Georgia O'Keeffe", "Andrew Wyeth"],
        correct: 0,
      },
      {
        id: 22,
        question: "Which dance is performed in tutus?",
        options: ["Jazz", "Ballet", "Modern", "Hip-hop"],
        correct: 1,
      },
      {
        id: 23,
        question: "What is a fresco?",
        options: ["Oil painting", "Watercolor", "Wall painting", "Sculpture"],
        correct: 2,
      },
      {
        id: 24,
        question: "Who composed 'The Magic Flute'?",
        options: ["Mozart", "Beethoven", "Haydn", "Schubert"],
        correct: 0,
      },
      {
        id: 25,
        question: "Which artist cut off his own ear?",
        options: ["Picasso", "van Gogh", "Gauguin", "Cézanne"],
        correct: 1,
      },
      {
        id: 26,
        question: "What is the art of paper folding called?",
        options: ["Kirigami", "Origami", "Ikebana", "Sumi-e"],
        correct: 1,
      },
      {
        id: 27,
        question: "Who painted 'The Scream'?",
        options: ["Edvard Munch", "Gustav Klimt", "Egon Schiele", "Wassily Kandinsky"],
        correct: 0,
      },
      {
        id: 28,
        question: "Which instrument has strings and is played with a bow?",
        options: ["Guitar", "Violin", "Piano", "Harp"],
        correct: 1,
      },
      {
        id: 29,
        question: "What is the art of arranging flowers called?",
        options: ["Origami", "Ikebana", "Bonsai", "Sumi-e"],
        correct: 1,
      },
      { id: 30, question: "Who painted 'Water Lilies'?", options: ["Renoir", "Monet", "Degas", "Manet"], correct: 1 },
      {
        id: 31,
        question: "Which building style has flying buttresses?",
        options: ["Romanesque", "Gothic", "Baroque", "Renaissance"],
        correct: 1,
      },
      { id: 32, question: "What is a sonnet?", options: ["A song", "A dance", "A poem", "A painting"], correct: 2 },
      {
        id: 33,
        question: "Who composed 'Für Elise'?",
        options: ["Mozart", "Beethoven", "Chopin", "Liszt"],
        correct: 1,
      },
      {
        id: 34,
        question: "Which art movement emphasized emotion over realism?",
        options: ["Realism", "Expressionism", "Classicism", "Naturalism"],
        correct: 1,
      },
      {
        id: 35,
        question: "What is the art of making pottery called?",
        options: ["Sculpting", "Ceramics", "Carving", "Molding"],
        correct: 1,
      },
      {
        id: 36,
        question: "Who painted 'Las Meninas'?",
        options: ["El Greco", "Velázquez", "Goya", "Murillo"],
        correct: 1,
      },
      {
        id: 37,
        question: "Which instrument is played by pressing keys and pedals?",
        options: ["Piano", "Organ", "Harpsichord", "Accordion"],
        correct: 1,
      },
      {
        id: 38,
        question: "What is the art of storytelling through movement?",
        options: ["Theater", "Dance", "Mime", "Opera"],
        correct: 1,
      },
      {
        id: 39,
        question: "Who painted 'The Birth of Venus'?",
        options: ["Leonardo", "Michelangelo", "Botticelli", "Raphael"],
        correct: 2,
      },
      {
        id: 40,
        question: "Which culture created totem poles?",
        options: ["Aztec", "Inuit", "Native American", "Aboriginal"],
        correct: 2,
      },
      {
        id: 41,
        question: "What is a haiku?",
        options: ["A painting", "A short poem", "A dance", "A song"],
        correct: 1,
      },
      {
        id: 42,
        question: "Who composed 'The Nutcracker'?",
        options: ["Stravinsky", "Tchaikovsky", "Prokofiev", "Rimsky-Korsakov"],
        correct: 1,
      },
      {
        id: 43,
        question: "Which art uses light and shadow dramatically?",
        options: ["Impressionism", "Chiaroscuro", "Pointillism", "Fauvism"],
        correct: 1,
      },
      {
        id: 44,
        question: "What is the art of making jewelry called?",
        options: ["Goldsmithing", "Silversmithing", "Jewelry making", "All of the above"],
        correct: 3,
      },
      { id: 45, question: "Who painted 'Guernica'?", options: ["Dalí", "Picasso", "Miró", "Gris"], correct: 1 },
      {
        id: 46,
        question: "Which dance originated in Spain?",
        options: ["Tango", "Flamenco", "Salsa", "Rumba"],
        correct: 1,
      },
      {
        id: 47,
        question: "What is the art of making stained glass windows?",
        options: ["Glazing", "Glasswork", "Vitreous art", "All of the above"],
        correct: 3,
      },
      {
        id: 48,
        question: "Who painted 'The Night Watch'?",
        options: ["Vermeer", "Rembrandt", "Rubens", "van Dyck"],
        correct: 1,
      },
      {
        id: 49,
        question: "Which instrument has 47 strings?",
        options: ["Guitar", "Harp", "Piano", "Violin"],
        correct: 1,
      },
      {
        id: 50,
        question: "What is the art of making tapestries called?",
        options: ["Weaving", "Embroidery", "Needlework", "Textile art"],
        correct: 0,
      },
    ],
  },
  {
    id: "music-basics",
    title: "Music Basics",
    description: "Instruments, composers, and music theory",
    icon: "Music",
    color: "bg-accent/10 text-accent",
    difficulty: "Easy",
    questions: [
      { id: 1, question: "How many strings does a guitar typically have?", options: ["4", "5", "6", "7"], correct: 2 },
      {
        id: 2,
        question: "What is the highest voice part in a choir?",
        options: ["Alto", "Soprano", "Tenor", "Bass"],
        correct: 1,
      },
      {
        id: 3,
        question: "Which composer wrote 'Ode to Joy'?",
        options: ["Mozart", "Beethoven", "Bach", "Chopin"],
        correct: 1,
      },
      { id: 4, question: "How many keys are on a standard piano?", options: ["76", "88", "96", "104"], correct: 1 },
      { id: 5, question: "What does 'forte' mean in music?", options: ["Soft", "Loud", "Fast", "Slow"], correct: 1 },
      // Continue with 45 more music questions...
      {
        id: 6,
        question: "Which instrument is known as the 'king of instruments'?",
        options: ["Piano", "Violin", "Organ", "Trumpet"],
        correct: 2,
      },
      {
        id: 7,
        question: "What are the lines that music is written on called?",
        options: ["Staff", "Scale", "Clef", "Measure"],
        correct: 0,
      },
      { id: 8, question: "How many beats are in a whole note?", options: ["1", "2", "3", "4"], correct: 3 },
      {
        id: 9,
        question: "Which family does the trumpet belong to?",
        options: ["String", "Woodwind", "Brass", "Percussion"],
        correct: 2,
      },
      {
        id: 10,
        question: "What is the lowest male voice part?",
        options: ["Tenor", "Baritone", "Bass", "Alto"],
        correct: 2,
      },
      // Adding more questions to reach 50
      {
        id: 11,
        question: "Which composer wrote 'The Four Seasons'?",
        options: ["Bach", "Vivaldi", "Handel", "Mozart"],
        correct: 1,
      },
      { id: 12, question: "What does 'piano' mean in music?", options: ["Loud", "Soft", "Fast", "Slow"], correct: 1 },
      { id: 13, question: "How many strings does a violin have?", options: ["3", "4", "5", "6"], correct: 1 },
      { id: 14, question: "Which note comes after G?", options: ["F", "A", "B", "C"], correct: 1 },
      {
        id: 15,
        question: "What is a group of musicians called?",
        options: ["Band", "Orchestra", "Ensemble", "All of the above"],
        correct: 3,
      },
      {
        id: 16,
        question: "Which instrument uses a reed?",
        options: ["Flute", "Clarinet", "Trumpet", "Trombone"],
        correct: 1,
      },
      { id: 17, question: "What does 'allegro' mean?", options: ["Slow", "Medium", "Fast", "Very fast"], correct: 2 },
      { id: 18, question: "How many lines are in a musical staff?", options: ["4", "5", "6", "7"], correct: 1 },
      {
        id: 19,
        question: "Which composer wrote 'Swan Lake'?",
        options: ["Stravinsky", "Tchaikovsky", "Prokofiev", "Rachmaninoff"],
        correct: 1,
      },
      {
        id: 20,
        question: "What is the symbol at the beginning of a staff called?",
        options: ["Note", "Clef", "Key", "Time"],
        correct: 1,
      },
      { id: 21, question: "Which instrument has pedals?", options: ["Guitar", "Violin", "Piano", "Flute"], correct: 2 },
      {
        id: 22,
        question: "What does 'crescendo' mean?",
        options: ["Getting louder", "Getting softer", "Getting faster", "Getting slower"],
        correct: 0,
      },
      { id: 23, question: "How many beats are in a quarter note?", options: ["1", "2", "3", "4"], correct: 0 },
      {
        id: 24,
        question: "Which family does the flute belong to?",
        options: ["String", "Woodwind", "Brass", "Percussion"],
        correct: 1,
      },
      {
        id: 25,
        question: "What is the distance between two notes called?",
        options: ["Scale", "Chord", "Interval", "Harmony"],
        correct: 2,
      },
      {
        id: 26,
        question: "Which composer wrote 'The Magic Flute'?",
        options: ["Mozart", "Beethoven", "Bach", "Haydn"],
        correct: 0,
      },
      {
        id: 27,
        question: "What does 'andante' mean?",
        options: ["Very slow", "Walking pace", "Fast", "Very fast"],
        correct: 1,
      },
      { id: 28, question: "How many spaces are in a musical staff?", options: ["3", "4", "5", "6"], correct: 1 },
      {
        id: 29,
        question: "Which instrument is played with mallets?",
        options: ["Piano", "Guitar", "Xylophone", "Violin"],
        correct: 2,
      },
      {
        id: 30,
        question: "What is a musical phrase that repeats called?",
        options: ["Verse", "Chorus", "Bridge", "Refrain"],
        correct: 3,
      },
      {
        id: 31,
        question: "Which composer wrote 'Für Elise'?",
        options: ["Mozart", "Beethoven", "Chopin", "Bach"],
        correct: 1,
      },
      {
        id: 32,
        question: "What does 'diminuendo' mean?",
        options: ["Getting louder", "Getting softer", "Getting faster", "Getting slower"],
        correct: 1,
      },
      { id: 33, question: "How many valves does a trumpet have?", options: ["2", "3", "4", "5"], correct: 1 },
      {
        id: 34,
        question: "Which note is in the middle of the piano?",
        options: ["Middle A", "Middle B", "Middle C", "Middle D"],
        correct: 2,
      },
      {
        id: 35,
        question: "What is a song for one voice called?",
        options: ["Duet", "Solo", "Trio", "Quartet"],
        correct: 1,
      },
      {
        id: 36,
        question: "Which composer wrote 'The Nutcracker'?",
        options: ["Stravinsky", "Tchaikovsky", "Prokofiev", "Rimsky-Korsakov"],
        correct: 1,
      },
      {
        id: 37,
        question: "What does 'staccato' mean?",
        options: ["Smooth", "Short and detached", "Loud", "Soft"],
        correct: 1,
      },
      { id: 38, question: "How many strings does a bass guitar have?", options: ["3", "4", "5", "6"], correct: 1 },
      {
        id: 39,
        question: "Which family does the drum belong to?",
        options: ["String", "Woodwind", "Brass", "Percussion"],
        correct: 3,
      },
      {
        id: 40,
        question: "What is the speed of music called?",
        options: ["Rhythm", "Tempo", "Beat", "Meter"],
        correct: 1,
      },
      {
        id: 41,
        question: "Which composer wrote 'Canon in D'?",
        options: ["Bach", "Pachelbel", "Handel", "Vivaldi"],
        correct: 1,
      },
      {
        id: 42,
        question: "What does 'legato' mean?",
        options: ["Short", "Smooth and connected", "Loud", "Fast"],
        correct: 1,
      },
      { id: 43, question: "How many keys are black on a piano?", options: ["32", "34", "36", "38"], correct: 2 },
      {
        id: 44,
        question: "Which instrument has a slide?",
        options: ["Trumpet", "Trombone", "French Horn", "Tuba"],
        correct: 1,
      },
      {
        id: 45,
        question: "What is a group of three notes played together?",
        options: ["Scale", "Chord", "Triad", "Harmony"],
        correct: 2,
      },
      {
        id: 46,
        question: "Which composer wrote 'Ave Maria'?",
        options: ["Schubert", "Bach", "Mozart", "All of the above"],
        correct: 3,
      },
      {
        id: 47,
        question: "What does 'ritardando' mean?",
        options: ["Getting louder", "Getting softer", "Getting faster", "Getting slower"],
        correct: 3,
      },
      {
        id: 48,
        question: "How many strings does a harp typically have?",
        options: ["40", "47", "52", "60"],
        correct: 1,
      },
      {
        id: 49,
        question: "Which note has the shortest duration?",
        options: ["Whole", "Half", "Quarter", "Sixteenth"],
        correct: 3,
      },
      {
        id: 50,
        question: "What is the study of music theory called?",
        options: ["Musicology", "Harmony", "Composition", "Analysis"],
        correct: 0,
      },
    ],
  },
  {
    id: "physics-fun",
    title: "Fun Physics",
    description: "Simple physics concepts and experiments",
    icon: "Zap",
    color: "bg-destructive/10 text-destructive",
    difficulty: "Hard",
    questions: [
      {
        id: 1,
        question: "What is the speed of light?",
        options: ["300,000 km/s", "150,000 km/s", "450,000 km/s", "600,000 km/s"],
        correct: 0,
      },
      {
        id: 2,
        question: "What force keeps us on the ground?",
        options: ["Magnetism", "Gravity", "Friction", "Pressure"],
        correct: 1,
      },
      {
        id: 3,
        question: "What happens to water at 100°C?",
        options: ["Freezes", "Boils", "Melts", "Evaporates"],
        correct: 1,
      },
      {
        id: 4,
        question: "What is the unit of electric current?",
        options: ["Volt", "Watt", "Ampere", "Ohm"],
        correct: 2,
      },
      {
        id: 5,
        question: "Which color has the longest wavelength?",
        options: ["Red", "Blue", "Green", "Violet"],
        correct: 0,
      },
      // Continue with 45 more physics questions...
      {
        id: 6,
        question: "What is the formula for force?",
        options: ["F = ma", "F = mv", "F = mc²", "F = mgh"],
        correct: 0,
      },
      {
        id: 7,
        question: "What type of energy does a moving object have?",
        options: ["Potential", "Kinetic", "Thermal", "Chemical"],
        correct: 1,
      },
      {
        id: 8,
        question: "What is the unit of frequency?",
        options: ["Meter", "Second", "Hertz", "Newton"],
        correct: 2,
      },
      {
        id: 9,
        question: "What happens to sound in a vacuum?",
        options: ["Gets louder", "Gets softer", "Cannot travel", "Changes pitch"],
        correct: 2,
      },
      {
        id: 10,
        question: "What is the acceleration due to gravity on Earth?",
        options: ["9.8 m/s²", "10 m/s²", "8.9 m/s²", "11 m/s²"],
        correct: 0,
      },
      // Adding more questions to reach 50
      { id: 11, question: "What is the unit of power?", options: ["Joule", "Watt", "Newton", "Pascal"], correct: 1 },
      {
        id: 12,
        question: "Which law states that energy cannot be created or destroyed?",
        options: ["Newton's First", "Conservation of Energy", "Ohm's Law", "Boyle's Law"],
        correct: 1,
      },
      { id: 13, question: "What is the unit of pressure?", options: ["Newton", "Pascal", "Joule", "Watt"], correct: 1 },
      {
        id: 14,
        question: "What type of wave is light?",
        options: ["Sound wave", "Electromagnetic wave", "Water wave", "Seismic wave"],
        correct: 1,
      },
      {
        id: 15,
        question: "What is the freezing point of water?",
        options: ["0°C", "32°C", "100°C", "-32°C"],
        correct: 0,
      },
      { id: 16, question: "What is the unit of work?", options: ["Newton", "Watt", "Joule", "Pascal"], correct: 2 },
      {
        id: 17,
        question: "Which particle has a positive charge?",
        options: ["Electron", "Proton", "Neutron", "Photon"],
        correct: 1,
      },
      {
        id: 18,
        question: "What is the speed of sound in air?",
        options: ["343 m/s", "300 m/s", "400 m/s", "500 m/s"],
        correct: 0,
      },
      {
        id: 19,
        question: "What is the unit of electric charge?",
        options: ["Ampere", "Volt", "Coulomb", "Ohm"],
        correct: 2,
      },
      {
        id: 20,
        question: "What type of energy does a stretched rubber band have?",
        options: ["Kinetic", "Potential", "Thermal", "Chemical"],
        correct: 1,
      },
      { id: 21, question: "What is the unit of resistance?", options: ["Volt", "Ampere", "Ohm", "Watt"], correct: 2 },
      {
        id: 22,
        question: "Which law describes the relationship between voltage, current, and resistance?",
        options: ["Newton's Law", "Ohm's Law", "Boyle's Law", "Charles' Law"],
        correct: 1,
      },
      {
        id: 23,
        question: "What is the unit of magnetic field strength?",
        options: ["Tesla", "Weber", "Henry", "Gauss"],
        correct: 0,
      },
      {
        id: 24,
        question: "What happens to the volume of a gas when temperature increases?",
        options: ["Decreases", "Increases", "Stays same", "Becomes zero"],
        correct: 1,
      },
      {
        id: 25,
        question: "What is the unit of momentum?",
        options: ["kg⋅m/s", "N⋅s", "Both A and B", "J⋅s"],
        correct: 2,
      },
      {
        id: 26,
        question: "Which color has the highest frequency?",
        options: ["Red", "Blue", "Green", "Violet"],
        correct: 3,
      },
      { id: 27, question: "What is the unit of energy?", options: ["Newton", "Watt", "Joule", "Pascal"], correct: 2 },
      {
        id: 28,
        question: "What type of current flows in one direction only?",
        options: ["AC", "DC", "Both", "Neither"],
        correct: 1,
      },
      {
        id: 29,
        question: "What is the unit of capacitance?",
        options: ["Farad", "Henry", "Ohm", "Siemens"],
        correct: 0,
      },
      {
        id: 30,
        question: "What happens to kinetic energy when speed doubles?",
        options: ["Doubles", "Triples", "Quadruples", "Stays same"],
        correct: 2,
      },
      { id: 31, question: "What is the unit of inductance?", options: ["Farad", "Henry", "Ohm", "Tesla"], correct: 1 },
      {
        id: 32,
        question: "Which particle has no electric charge?",
        options: ["Electron", "Proton", "Neutron", "Ion"],
        correct: 2,
      },
      {
        id: 33,
        question: "What is the unit of luminous intensity?",
        options: ["Lumen", "Candela", "Lux", "Watt"],
        correct: 1,
      },
      {
        id: 34,
        question: "What type of lens converges light rays?",
        options: ["Concave", "Convex", "Plane", "Cylindrical"],
        correct: 1,
      },
      {
        id: 35,
        question: "What is the unit of radioactivity?",
        options: ["Becquerel", "Gray", "Sievert", "Roentgen"],
        correct: 0,
      },
      {
        id: 36,
        question: "What happens to resistance when temperature increases in metals?",
        options: ["Increases", "Decreases", "Stays same", "Becomes zero"],
        correct: 0,
      },
      {
        id: 37,
        question: "What is the unit of luminous flux?",
        options: ["Candela", "Lumen", "Lux", "Steradian"],
        correct: 1,
      },
      {
        id: 38,
        question: "Which law states that for every action there is an equal and opposite reaction?",
        options: ["First Law", "Second Law", "Third Law", "Law of Gravitation"],
        correct: 2,
      },
      {
        id: 39,
        question: "What is the unit of solid angle?",
        options: ["Radian", "Steradian", "Degree", "Gradian"],
        correct: 1,
      },
      {
        id: 40,
        question: "What type of wave requires a medium to travel?",
        options: ["Light wave", "Radio wave", "Sound wave", "X-ray"],
        correct: 2,
      },
      {
        id: 41,
        question: "What is the unit of electric potential?",
        options: ["Ampere", "Volt", "Ohm", "Coulomb"],
        correct: 1,
      },
      {
        id: 42,
        question: "What happens to the period of a pendulum when length increases?",
        options: ["Increases", "Decreases", "Stays same", "Becomes zero"],
        correct: 0,
      },
      {
        id: 43,
        question: "What is the unit of thermal conductivity?",
        options: ["W/(m⋅K)", "J/(kg⋅K)", "W/m²", "J/s"],
        correct: 0,
      },
      {
        id: 44,
        question: "Which type of radiation has the highest penetrating power?",
        options: ["Alpha", "Beta", "Gamma", "X-ray"],
        correct: 2,
      },
      {
        id: 45,
        question: "What is the unit of specific heat capacity?",
        options: ["J/K", "J/(kg⋅K)", "W/K", "cal/g"],
        correct: 1,
      },
      {
        id: 46,
        question: "What happens to wavelength when frequency increases?",
        options: ["Increases", "Decreases", "Stays same", "Becomes zero"],
        correct: 1,
      },
      { id: 47, question: "What is the unit of angular velocity?", options: ["rad/s", "m/s", "Hz", "rpm"], correct: 0 },
      {
        id: 48,
        question: "Which principle explains how airplanes fly?",
        options: ["Archimedes", "Bernoulli", "Pascal", "Boyle"],
        correct: 1,
      },
      { id: 49, question: "What is the unit of torque?", options: ["N⋅m", "J", "W", "Pa"], correct: 0 },
      {
        id: 50,
        question: "What type of interference occurs when waves are in phase?",
        options: ["Destructive", "Constructive", "Partial", "Complete"],
        correct: 1,
      },
    ],
  },
]

export function getQuizById(id: string): Quiz | undefined {
  return quizzes.find((quiz) => quiz.id === id)
}

export function getRandomQuestions(quiz: Quiz, count: number): Question[] {
  const shuffled = [...quiz.questions].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}
